// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Account  string `json:"account"`
	Password string `json:"password"`
}

type Response struct {
	UserAccount  string `json:"account"`
	UserName     string `json:"name"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}
