// Code generated by goctl. DO NOT EDIT.
package types

type CheckResponse struct {
	Account   string `json:"account"`
	Remaining int    `json:"remaining"`
	Balance   int    `json:"balance"`
}

type OpenResponse struct {
	Account   string `json:"account"`
	Amount    int    `json:"amount"`
	Remaining int    `json:"remaining"`
	Balance   int    `json:"balance"`
}
